# -*- coding: utf-8 -*-
"""Assignment_4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/15BT2x2dSQ61IZjIp4y5LWzsTaEgSqWoU
"""

pip install Faker

pip install Dumper

from faker import Faker
import pandas as pd
import random 
import matplotlib.pyplot as plt
import seaborn as sns
from random import  randint
import json
import numpy as np

fake = Faker()

"""### User Details"""

df_user = pd.DataFrame(columns=('UserID','Name','Age','Address','latitude','longitude'))

for i in range(1000):
    userdetails = [fake.random_int(1, 100),
            fake.name(),
            randint(1, 80),
            fake.address(),
             str(fake.latitude()),
             str(fake.longitude())]
    df_user.loc[i] = [item for item in userdetails]

df_user.to_csv('/content/drive/My Drive/Aassignment_4/userdetails.csv')

df_user.head()

"""### Department Details"""

df_dept = {'DepartmentID': ['1', '2','3'], 'DepartmentName': ['Coffee', 'Fruits','Food']}
df_dept = pd.DataFrame(df_dept)

df_dept.head()

df_dept.to_csv('/content/drive/My Drive/Aassignment_4/deptdetails.csv')

"""### Product Details"""

df_product = pd.DataFrame(columns=('DepartmentID','ProductID'))

for i in range(1000):
    productdetails = [fake.random_int(1, 3),
            # np.random.choice(product, 1),
            fake.random_int(1, 6),
            ]
    df_product.loc[i] = [item for item in productdetails]

products = ('Chips','Granola & Trail Mix','Hot Coffee','Cold Coffee','Dry Fruits','Fruit Juice')

prod1 = (1,2)
df_product["prod1"] = np.random.choice(list(prod1),1000,p=[0.4, 0.6])

prod2 = (3,4)
df_product["prod2"] = np.random.choice(list(prod2),1000,p=[0.4, 0.6])

prod3 = (5,6)
df_product["prod3"] = np.random.choice(list(prod3),1000,p=[0.4, 0.6])

df_product.loc[(df_product['DepartmentID'] == 1) , 'ProductID'] = df_product["prod1"]
df_product.loc[(df_product['DepartmentID'] == 1) & (df_product['ProductID'] == 1), 'ProductName'] = "Hot Coffee"
df_product.loc[(df_product['DepartmentID'] == 1) & (df_product['ProductID'] == 2), 'ProductName'] = "Cold Coffee"

df_product.loc[(df_product['DepartmentID'] == 2) , 'ProductID'] = df_product["prod2"]
df_product.loc[(df_product['DepartmentID'] == 2) & (df_product['ProductID'] == 3), 'ProductName'] = "Dry Fruits"
df_product.loc[(df_product['DepartmentID'] == 2) & (df_product['ProductID'] == 4), 'ProductName'] = "Fruit Juice"

df_product.loc[(df_product['DepartmentID'] == 3) , 'ProductID'] = df_product["prod3"]
df_product.loc[(df_product['DepartmentID'] == 3) & (df_product['ProductID'] == 5), 'ProductName'] = "Chips"
df_product.loc[(df_product['DepartmentID'] == 3) & (df_product['ProductID'] == 6), 'ProductName'] = "Granola & Trail Mix"

df_product['ProductName'].value_counts()

df_product = df_product.drop(columns=(["prod1","prod2","prod3"]),axis=1)

df_product.to_csv('/content/drive/My Drive/Aassignment_4/proddetails.csv')

"""### Purchase Details"""

df_purchase = pd.DataFrame(columns=('UserID',
                                    'SnackID',
                                    'Rating',
                                    'TimeStamp'))

for i in range(1000):
    stuff = [fake.random_int(100, 115),
            fake.random_int(1, 15)
        # , fake.random_int(1, 5)
        ,np.random.choice(6,  p=[0.01, 0.25, 0.3, 0.15, 0.2,0.09])
        , fake.date_time_between(start_date='-1y', end_date='now', tzinfo=None)]
    df_purchase.loc[i] = [item for item in stuff]

df_purchase['Rating'].value_counts()

df_purchase.loc[df_purchase['SnackID'] == 1, 'SnackDescription'] = 'Mocha Latte Coffee'
df_purchase.loc[df_purchase['SnackID'] == 2, 'SnackDescription'] = 'Vanilla Chai'
df_purchase.loc[df_purchase['SnackID'] == 3, 'SnackDescription'] = 'Expresso'
df_purchase.loc[df_purchase['SnackID'] == 4, 'SnackDescription'] = 'Cold Brew'
df_purchase.loc[df_purchase['SnackID'] == 5, 'SnackDescription'] = 'Ice Coffee'
df_purchase.loc[df_purchase['SnackID'] == 6, 'SnackDescription'] = 'Iced Cappacino'
df_purchase.loc[df_purchase['SnackID'] == 7, 'SnackDescription'] = 'Banana Juice'
df_purchase.loc[df_purchase['SnackID'] == 8, 'SnackDescription'] = 'Apple Juice'
df_purchase.loc[df_purchase['SnackID'] == 9, 'SnackDescription'] = 'Almonds Pack'
df_purchase.loc[df_purchase['SnackID'] == 10, 'SnackDescription'] = 'Pistachios Pack'
df_purchase.loc[df_purchase['SnackID'] == 11, 'SnackDescription'] = 'Cashew nut Pack'
df_purchase.loc[df_purchase['SnackID'] == 12, 'SnackDescription'] = 'Pringles'
df_purchase.loc[df_purchase['SnackID'] == 13, 'SnackDescription'] = 'Cape Cod Chips'
df_purchase.loc[df_purchase['SnackID'] == 14, 'SnackDescription'] = 'Doritos'
df_purchase.loc[df_purchase['SnackID'] == 15, 'SnackDescription'] = 'Snickers'
df_purchase.loc[df_purchase['SnackID'] == 16, 'SnackDescription'] = 'Oreo Cookies'
df_purchase.loc[df_purchase['SnackID'] == 17, 'SnackDescription'] = 'Breakfast Bars'

df_purchase.loc[(df_purchase['SnackID'] == 1) | (df_purchase['SnackID'] == 2) | (df_purchase['SnackID'] == 3), 'ProductID'] = 1
df_purchase.loc[(df_purchase['SnackID'] == 4) | (df_purchase['SnackID'] == 5) | (df_purchase['SnackID'] == 6), 'ProductID'] = 2

df_purchase.loc[(df_purchase['SnackID'] == 7) | (df_purchase['SnackID'] == 8) , 'ProductID'] = 3
df_purchase.loc[(df_purchase['SnackID'] == 9) | (df_purchase['SnackID'] == 10) | (df_purchase['SnackID'] == 11), 'ProductID'] = 4

df_purchase.loc[(df_purchase['SnackID'] == 12) | (df_purchase['SnackID'] == 13) | (df_purchase['SnackID'] == 14), 'ProductID'] = 5
df_purchase.loc[(df_purchase['SnackID'] == 15) | (df_purchase['SnackID'] == 16) | (df_purchase['SnackID'] == 17), 'ProductID'] = 6

df_purchase.loc[(df_purchase['SnackID'] == 2)]

df_purchase['ProductID'] = df_purchase['ProductID'].astype(int)

df_purchase.head()

df_purchase.to_csv('/content/drive/My Drive/Aassignment_4/purchasedetails.csv')

fig_dims = (25, 7)
fig, ax = plt.subplots(figsize=fig_dims)
sns.barplot(x = "SnackDescription", y = "Rating", ax=ax, data=df_purchase.sort_values('Rating'))