# -*- coding: utf-8 -*-
"""ADM_Project_Fake Data.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1goW95OuxnKVk-TW48DeIDy1pdbt3n4Ei

### Libraries
"""

pip install Faker

pip install Dumper

from faker import Faker
import pandas as pd
import random 
import matplotlib.pyplot as plt
import seaborn as sns
from random import  randint
import json
import numpy as np

faker = Faker()

"""## Dataset"""

df = pd.read_csv("/content/drive/My Drive/ADM Project/Dataset/ratings.csv")

df.head()

"""## User Dataset"""

user = df.drop(columns=["book_id","rating"],axis=1)

user = user.drop_duplicates()

lst = []
for n in range(len(user)):
     lst.append({ 'First Name': faker.name(),
                 'Age' : randint(1, 80),
                 'Maritial Status' : randint(0,1),
                  'Occupation': faker.job(),
                  'Lat': faker.coordinate(center=74.0, radius=0.10),
                  'Lon': faker.coordinate(center=40.8, radius=0.10),
                  'City' : faker.city(),  # random metro cities
                 
              })

df_user = pd.DataFrame(lst)

df_user.head()

df_user['City'].value_counts()

df_user['user_id'] = user[user.user_id.notnull()].reset_index().drop(columns='index')

df_user.head()

df_user.to_csv('/content/drive/My Drive/ADM Project/Dataset/user_details.csv')

"""## Books Price Dataset"""

books = df.drop(columns=["user_id","rating"],axis=1)

books = books.drop_duplicates()

books.head()

bookslst = []
for n in range(len(books)):
     bookslst.append({'Price' : randint(15, 80),
              })

df_books = pd.DataFrame(bookslst)

df_books['book_id'] = books[books.book_id.notnull()].reset_index().drop(columns='index')

df_books.head()

df_books.to_csv('/content/drive/My Drive/ADM Project/Dataset/books_price.csv')

"""## RFM Dataset"""

df_rating = df

df[df['user_id']==2]

df_rating = df_rating.merge(df_books,how='inner',on='book_id')

# df_rating[df_rating['book_id']==4081]

df_rating.head()

ls_invoicedate = []
for i in range(len(df_rating)):
  ls_invoicedate.append({'Invoice_Date' : fake.date_time_between(start_date='-1y', end_date='now', tzinfo=None),
                         'Quantity' : random.randint(1,5),
                         'Invoice Number' : 1
              })

df_rfmdata = pd.DataFrame(ls_invoicedate)

df_rfmdata = df_rfmdata.rename(columns={'Invoice Number':'invoice_num'})

quan = df_rfmdata

quan

quan = quan.drop(columns=["Invoice_Date","invoice_num"],axis=1)

invoice_number = df_rfmdata

invoice_number = invoice_number.drop(columns=["Quantity","Invoice_Date"],axis=1)

invoicedate = df_rfmdata

invoicedate = invoicedate.drop(columns=["Quantity","invoice_num"],axis=1)

df_rating['invoice_date'] = invoicedate[invoicedate.Invoice_Date.notnull()].reset_index().drop(columns='index')

df_rating['Quantity'] = quan[quan.Quantity.notnull()].reset_index().drop(columns='index')

df_rating['Invoice_Number'] = invoice_number[invoice_number.invoice_num.notnull()].reset_index().drop(columns='index')

df_rating.head()

df_rating.to_csv('/content/drive/My Drive/ADM Project/Dataset/rfm_data.csv')